export const typeListAll = [
  { slot: 0, type: { name: "normal" } },
  { slot: 0, type: { name: "fighting" } },
  { slot: 0, type: { name: "flying" } },
  { slot: 0, type: { name: "poison" } },
  { slot: 0, type: { name: "ground" } },
  { slot: 0, type: { name: "rock" } },
  { slot: 0, type: { name: "bug" } },
  { slot: 0, type: { name: "ghost" } },
  { slot: 0, type: { name: "steel" } },
  { slot: 0, type: { name: "fire" } },
  { slot: 0, type: { name: "water" } },
  { slot: 0, type: { name: "grass" } },
  { slot: 0, type: { name: "electric" } },
  { slot: 0, type: { name: "psychic" } },
  { slot: 0, type: { name: "ice" } },
  { slot: 0, type: { name: "dragon" } },
  { slot: 0, type: { name: "dark" } },
  { slot: 0, type: { name: "fairy" } },
];
